# Generated by Django 5.2.8 on 2025-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_user_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='subscribers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='video',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
